### ISSUE TITLE
Added support for CORS but requires patching remy as well

### ISSUE THREAD

**Issue by soapdog** [sailorproject/sailor#128]
Those using sailor to build API servers need some more advanced controls for dealing with HTTP headers. One common need is implementing CORS support so that the API server is able to respond to clients on different origins, [this is all done through some juggling of HTTP headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#The_HTTP_response_headers).

To solve CORS, I have implemented a new function called [```page:enable_cors()```](https://github.com/amora-labs/sailor/blob/enhancement-cors/src/sailor/page.lua#L162) which allows the developer to set all needed headers but to make this work, I also need to patch *remy* because the cgilua implementation there only outputs *location* headers and ignore all the rest.

I have already [sent a PR to remy fixing this](https://github.com/felipedaragon/remy/pull/11) and am waiting for feedback. Since this PR blocks the current CORS implementation on Xavante (but potentially not on Apache) I decided not to send the PR to sailor right now.

In the meanwhile, you can check the implementation here: 

  https://github.com/amora-labs/sailor/tree/enhancement-cors (on page.lua)

Cheers
andre

**Comment by Etiene** [comment]
Seems like the PR is merged! I'm gonna make a new remy release :)  Then you can make a PR to sailor with this! 💃

**Comment by Etiene** [comment]
Done! You can PR this to sailor now! :D

**Comment by felipedaragon** [comment]
Merged in Remy as well _o/

**Comment by soapdog** [comment]
PR sent https://github.com/sailorproject/sailor/pull/131 :D :D
