### ISSUE TITLE
The project website and it's repo are lost in a limbo

### ISSUE THREAD

**Issue by xspager** [sailorproject/sailor#135]
Hey! The repo https://github.com/sailorproject/sailor_website/ and the site http://sailorproject.org/ are both sad for lack of attention 😞 😭.  Who gonna slay the ⚔ 🐉 of sadness? 

Please, bring their joy back. 😅

**Comment by Etiene** [comment]
I'm slowly getting back to things :)

**Comment by Etiene** [comment]
merged and pulled!
