### ISSUE TITLE
Can't make Sailor application

### ISSUE THREAD

**Issue by Nbotz** [sailorproject/sailor#144]
`/usr/bin/lua5.1: ...usr/local/lib/luarocks/rocks/sailor/0.5-4/bin/sailor:41: attempt to index a nil value
stack traceback:
	...usr/local/lib/luarocks/rocks/sailor/0.5-4/bin/sailor:41: in function 'get_sailor_path'
	...usr/local/lib/luarocks/rocks/sailor/0.5-4/bin/sailor:68: in function 'create'
	...usr/local/lib/luarocks/rocks/sailor/0.5-4/bin/sailor:146: in function 'run'
	...usr/local/lib/luarocks/rocks/sailor/0.5-4/bin/sailor:156: in main chunk
	[C]: ?
`
I get this error everytime i attempt to create a sailor app. I'm using Debian, and installed sailor through luarocks.

**Comment by xspager** [comment]
Hi! Try cloning the head of the repo and installing it with luarocks make, like:
```bash
$ git clone https://github.com/sailorproject/sailor
$ cd sailor
$ luarocks make
```
then try to create the app again :)

**Comment by carc1n0gen** [comment]
@xspager I had this issue today.  Was wondering if there is a way to install this to your user folder like `luarocks install --local <package>` does?

**Comment by Etiene** [comment]
@Nbotz & @carc1n0gen were you able to solve this? Sorry for the delay in replying. I'm cleaning the issues now. Please ping me in the next weeks if you still need help or I'll close this.

**Comment by carc1n0gen** [comment]
I never went any further with this. Feel free to close

**Comment by Etiene** [comment]
My apologies once again for being away! 
all the best
