### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by cnyyk** [sailorproject/sailor#145]
I'm waiting for 1.0 release for using in production while I read this article:
http://lua.space/webdev/the-best-lua-web-frameworks

But one years later, there's nothing happened.

So, is this project dead or not?

**Comment by Etiene** [comment]
I'm really sorry! No, it's not dead. I just had to move countries and do visa applications  **twice**  and finish a master thesis! I'm getting back to it in the next couple of weeks. In the meantime contributions are welcome and if there are any features you are looking for specifically we can start discussion & design at our mailing list for the moment.

https://groups.google.com/forum/#!forum/sailor-l/join
