### ISSUE TITLE
Why the documentation differs in repo and on sailorproject.org?

### ISSUE THREAD

**Issue by d9k** [sailorproject/sailor#160]
Hello! I noticed that the doc on the sailorproject.org and sailor repo differs.
How could it be?

1. https://github.com/sailorproject/sailor/blob/master/docs/INSTALL_LINUX.md

> If you don't have it already, install Lua. Sailor is compatible with both 5.1 and 5.2.
> sudo apt-get install lua5.1

2. http://www.sailorproject.org/docs/install_linux

> If you don't have it already, install Lua. Sailor is compatible with both 5.1 and 5.2.
> sudo apt-get install lua5.2

At first I thought there exist special branch for documentation.. But I don't observe it.

**Comment by d9k** [comment]
Ok, I see..
Another repo, documentation is not synced

https://github.com/sailorproject/sailor_website/blob/master/docs/0.5/INSTALL_LINUX.md

**Comment by CodelessFuture** [comment]
Sorry for the late reply. 
All these problems will disappear with version 0.6.0 from which I will be able to manage the project in full, including the updates and the deployment of the new site.
I hope for the first half of march.
