### ISSUE TITLE
sailorproject.org now directs to unrelated wordpress site

### ISSUE THREAD

**Issue by ryanford** [sailorproject/sailor#178]
![image](https://user-images.githubusercontent.com/20901017/81641781-66bc4680-9454-11ea-92f3-075fea985e41.png)

**Comment by Etiene** [comment]
Thanks for reporting. I have not found new maintainers for the project and it simply fell into abandonment. It looks like I lost the domain. Someone can feel free to re-host and reshape it if they wish. All the files for the old website are here: https://github.com/sailorproject/sailor_website

**Comment by d9k** [comment]
@Etiene, thanks for all of your work! 
Sailor was the best project on Github, IMHO

>  I have not found new maintainers for the project and it simply fell into abandonment

unfortunately, life of an office worker ate pretty much all of my time and energy too, so I have no ability to become maintainer too. I wish someday politicians will provide us basic income so we will have more freedom of choosing the project to work on

**Comment by ricardoG08** [comment]
finish 2020, Sailors works with OpenResty, documentation:

http://w.etiene.net/index.lua

**Comment by ricardoG08** [comment]
please continue Sailor 😭
