### ISSUE TITLE
Document compatibility with Lua 5.3

### ISSUE THREAD

**Issue by Humbedooh** [sailorproject/sailor#64]
I assume this would still work? Regardless, a yes/no in the docs would be appreciated.

**Comment by Etiene** [comment]
As far as I've tested it is not compatible and it is documented on the github readme and first line of docs overview on website.

I've just added a small badge to github readme as well to show this. 

I should make new tests for 5.3 though, to see how it goes...

**Comment by Humbedooh** [comment]
I was looking at http://sailorproject.org/docs/?r=docs and it just made me wonder "does it work with 5.3 and just isn't updated on the site yet?" - something like "support for 5.3 in the works" would maybe help there.

**Comment by Etiene** [comment]
I'm not even sure if it is possible, not because of Sailor itself but because of dependencies... :/ 

Btw, speaking of that, will it 5.3 work on Apache?

**Comment by Humbedooh** [comment]
AIUI, Fedora22 ships with mod_lua using 5.3 - so it _should_ work.
