### ISSUE TITLE
Fix URLs in docs

### ISSUE THREAD

**Issue by Yonaba** [sailorproject/sailor#66]
Hi @Etiene,

I was peeking at the docs (well-written materials, by the way). I noticed something odd on the [installation](http://sailorproject.org/docs/install) guide page. There are four links provided which are supposed to redirects to the "how-to install" Sailor on Linux, Windows and Mac tutorials.
Except that, they do not. They just redirect to the installation page itself. It just seems something went wrong when resolving URLs when generating the docs. 

Can you take a look at that ?

Best regards.

**Comment by Etiene** [comment]
This is odd! It was working the other minute and I didn't alter it! Thanks for pointing :) Gonna check it now!

**Comment by Etiene** [comment]
Oh, I misinterpreted what you said earlier! Anyway, it's fixed now! Thanks for reporting :dancer:
