### ISSUE TITLE
Lua-bcrypt won't run on travis-ci environment

### ISSUE THREAD

**Issue by Etiene** [sailorproject/sailor#81]
help :~ 
our automated tests are gone :~
Travis has an old glibc version, I've tried all the impossible things to update it without success.

**Comment by xspager** [comment]
I think the build https://travis-ci.org/sailorproject/sailor/jobs/109029711 need you to specify the install of the package mysql-server, that might do the trick.

**Comment by Etiene** [comment]
you're looking at a different branch where I'm experimenting a different OS in travis now, but it doesnt have mysql service and something is wrong with postgres too. 

Take a look at the master branch https://travis-ci.org/sailorproject/sailor/jobs/109024428

**Comment by Etiene** [comment]
More details: https://github.com/mikejsavage/lua-bcrypt/issues/8

**Comment by Etiene** [comment]
#https://github.com/mikejsavage/lua-bcrypt/issues/8

**Comment by xspager** [comment]
If you use the trusty version of Ubuntu you can avoid the problem when dynamically linking, but looks like this list the changes you have to expect on Travis https://docs.travis-ci.com/user/database-setup/#MySQL-5.6

**Comment by Etiene** [comment]
Exactly. Not having the mysql service just means I have to manually install it and change things, which is already a pita, but I'm more worried about what's going on with postgres. Hopefully we'll get bcrypt to work on precise build so we don't have to worry about all that.

**Comment by Etiene** [comment]
Fixed!! https://github.com/mikejsavage/lua-bcrypt/issues/8
