### ISSUE TITLE
[Design] Architecture of adding extensions

### ISSUE THREAD

**Issue by Etiene** [sailorproject/sailor#82]
Please, let's discuss the architecture of adding extensions to Sailor!

Suppose someone wants to integrate a specific library to sailor and create a wrapper around it or just create a ready to go small sailor module, for example:

A login system with a user model, a controller and some views. 

And that this would have a rockspec and other people could just do something like:
```
luarocks install sailor-login
cd /path/to/my_app
sailor add login
```

I'd like suggestions on how to organize this and implement whatever's needed on sailor to enable this. 

List of things we need to think about
* namespace
* conflict between extensions
* different types of extentions, ex.: 
     * a new logging system for sailor, that changes nothing on your app, just a new library that can be required x
     * a whole pack with views to be added to an app, like the login system

**Comment by xspager** [comment]
I try to look on the way other frameworks do but (I'll look more into it) Django do like middlewares are layers of a onion and the request and responses pass through the layers coming from the browser and returning in the reverse order back as a response (see [Middleware](https://docs.djangoproject.com/en/1.9/topics/http/middleware/)), each extension can call for the registration (on the conf.lua of the application) so it can do its magic. Templates can be looked for on each extension path give the extension is listed on conf.lua. As the resgister of URL and controllers, maybe the way they do can be good for us too https://docs.djangoproject.com/en/1.9/intro/tutorial01/#creating-the-polls-app

Maybe we should be awere of not becaming Django for Lua or something :grin:

**Comment by develCuy** [comment]
I think we can follow how Lua works and how others solved this issue already. If we are supporting extensions, then it would be nice to let the community register the extensions they build in the project website, that will help build community of developers dedicated to contribute extensions. Talking about namespaces, I like how luasql and luadbi are packaged, they have drivers for different SQL servers/libraries, each driver registers under a centralized Lua module. If we provide clear documentation an examples on how to build a Sailor extension, along with an extensions registry, then this can scale real big.

**Comment by develCuy** [comment]
Just noticed that something we need to figure out is patching extensions. For servers running several sailor apps, they might share several modules but eventually one of the apps would need a patched version of a certain extension and the others just use what luarocks installed.
How about doing something like PHP's composer? It is a really helped in terms of being able to track where exactly the extensions are being loaded from, along with version number and other goodies. Perhaps dreaming to much but the design should allow codebase flexibility IMHO.
