### ISSUE TITLE
sailor create doesn't work when spaces in path present

### ISSUE THREAD

**Issue by louis77** [sailorproject/sailor#83]
`➜  sailor create "OB Testclient"  `

`sh: -c: line 0: syntax error near unexpected token `('
sh: -c: line 0: `cp -a /usr/local/share/lua/5.2/sailor/blank-app /Users/louis/My Projects/Git/ob_testclient'
/usr/local/bin/lua: /usr/local/lib/luarocks/rocks-5.2/sailor/0.5-3/bin/sailor:72: exit
stack traceback:
	[C]: in function 'assert'
	/usr/local/lib/luarocks/rocks-5.2/sailor/0.5-3/bin/sailor:72: in function 'create'
	/usr/local/lib/luarocks/rocks-5.2/sailor/0.5-3/bin/sailor:146: in function 'run'
	/usr/local/lib/luarocks/rocks-5.2/sailor/0.5-3/bin/sailor:156: in main chunk
	[C]: in ?`

**Comment by Etiene** [comment]
thanks for reporting and for the fix! :dancer:
