### ISSUE TITLE
Cannot quit server with CTRL-C / OS X

### ISSUE THREAD

**Issue by louis77** [sailorproject/sailor#85]
When I run Sailor in OS X Terminal with
`lua start-server.lua`
there is no way to quit, CTRL-C doesn't work.

The only way to get out of the process is by putting it into the backgroup (CTRL-Z) and killing the process manually (kill -9).

**Comment by xspager** [comment]
Have you tried, CTRL-C twice? This is Lua interpreter behavior.

**Comment by louis77** [comment]
I've tried twice and more, didn't work. But I found out that to exit Sailor I can press CTRL-C, then make a request in the browser and Sailor will exit. It's a bit annoying. Is there no other way to catch CTRL-C signal?

**Comment by malachaifrazier** [comment]
@louis77 perhaps this is what you're looking for? It should add Signal handlers using lua-ev http://stackoverflow.com/a/19800506
