### ISSUE TITLE
Sailor not installing on Linux Mint 17.1

### ISSUE THREAD

**Issue by felipedaragon** [sailorproject/sailor#89]
Tried to install Sailor in Mint 17.1 Cinnamon 32bit. I was able to install luarocks after making a sudo apt-get update. But then when calling luarocks install sailor I ran into something different:
(...)
cp: cannot stat ‘valua.lua’: No such file or directory

Error: Failed installing dependency: http://luarocks.org/repositories/rocks/valua-0.3-1.src.rock - Failed copying valua.lua

**Comment by Etiene** [comment]
As mentioned [here](https://github.com/sailorproject/sailor/issues/88), your luarocks version is 2.0.8, please update it before we narrow this down :)

**Comment by felipedaragon** [comment]
@Etiene configure gave a lot more info: ~/luarocks $ ./configure
Lua interpreter found: /usr/bin/lua...
Lua version detected: 5.1
lua found in $PATH: /usr/bin
Checking Lua includes... lua.h found in /usr/include/lua5.1/lua.h (Debian/Ubuntu)
wget found at /usr/bin
md5sum found at /usr/bin
Configuring for system... Linux
Configuring for architecture... i686
Using unversioned rocks dir: /usr/local/lib/luarocks/rocks
Writing configuration...

Installation prefix: /usr/local
LuaRocks configuration directory: /usr/local/etc/luarocks
Using Lua from: /usr

Done configuring.
- Type 'make build' and 'make install':
  to install to /usr/local as usual.
- Type 'make bootstrap':
  to install LuaRocks in /usr/local as a rock.

**Comment by Etiene** [comment]
Nothing unusual with that. Have you updated the version now?

**Comment by felipedaragon** [comment]
Nope, after make install I get ~/luarocks $ luarocks
lua5.1: /usr/local/share/lua/5.1/luarocks/help.lua:14: attempt to call field 'this_program' (a nil value)
stack traceback:
	/usr/local/share/lua/5.1/luarocks/help.lua:14: in main chunk
	[C]: in function 'require'
	/usr/bin/luarocks:10: in main chunk
	[C]: ?

**Comment by felipedaragon** [comment]
Before this I tried upgrading with ap-get but it would say that 2.0.8 was the latest release

**Comment by Etiene** [comment]
apt-get version is very outdated and I think it won't let you do `luarocks install luarocks` to update it. Self update was introduced after that... So downloading and compiling it is. But I am not sure why you are unable to do `make install`, I have not got this error before, maybe you should try opening an issue within [luarocks](https://github.com/keplerproject/luarocks). Are you running it with `sudo`?

**Comment by felipedaragon** [comment]
Yes, I used sudo.

**Comment by Etiene** [comment]
Submit an issue to luarocks itself like I mentioned, then :)

**Comment by felipedaragon** [comment]
Worked after following Hisham instructions at https://github.com/keplerproject/luarocks/issues/505 o/

Updating manifest for /usr/local/lib/luarocks/rocks
sailor 0.5-4 is now built and installed in /usr/local (license: MIT)
