### ISSUE TITLE
Update bootstrap shipped with sailor applications

### ISSUE THREAD

**Issue by Etiene** [sailorproject/sailor#91]
Sailor has a copy of bootstrap (http://getbootstrap.com/) that is deployed along with its web application. It's currently outdated and we need to replace with a newer version.

To-do:
* Update the one inside `dev/test-app`
* Update the one inside `src/sailor/blank-app`

This is a beginner-level issue, suitable for new contributors to Sailor and/or open source. I will guide through the git & github process if necessary :+1: 

This contribution will make part of the next release.

**Comment by avichalp** [comment]
Hi @Etiene,

I have updated the bootstrap files that you pointed out with the newer version of boostrap i.e. v3.3.6.
Please take a look at the PR [here] (https://github.com/sailorproject/sailor/pull/95).

**Comment by Etiene** [comment]
Thanks for your PR! It is now merged! :dancer:
